const worldTemplates = {
  fantasy: {
    characters: true,
    locations: true,
    factions: true,
    items: true,
    events: true,
    languages: true,
    abilities: true,
    powerSystem: true,
    creatures: true,
    religion: true,
    story: true,
    races: true,
    economy: true,
  },
  cyberpunk: {
    characters: true,
    locations: true,
    factions: true,
    items: true,
    events: true,
    languages: true,
    abilities: true,
    technology: true,
    powerSystem: true,
    creatures: true,
    story: true,
    economy: true,
  },
  postapocalyptic: {
    characters: true,
    locations: true,
    factions: true,
    items: true,
    events: true,
    abilities: true,
    creatures: true,
    story: true,
    races: true,
    economy: true,
  },
  romance: {
    characters: true,
    locations: true,
    factions: true,
    items: true,
    events: true,
    languages: true,
    story: true,
  },
  horror: {
    characters: true,
    locations: true,
    factions: true,
    items: true,
    events: true,
    abilities: true,
    creatures: true,
    religion: true,
    story: true,
  }
};

module.exports = worldTemplates;
